/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rtrk_myapplication_MyNDK */

#ifndef _Included_com_rtrk_myapplication_MyNDK
#define _Included_com_rtrk_myapplication_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rtrk_myapplication_MyNDK
 * Method:    increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_rtrk_myapplication_MyNDK_increment
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
